name: mermaid_dart
description: A pure Dart implementation of Mermaid's parser and renderer.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.12.2

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  petitparser: ^7.0.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
